### ISSUE TITLE
Could you possibly add infini-attention and not this thing whatever this was supposed to be

### ISSUE THREAD

**Issue by DanFosing** [kyegomez/Infini-attention#7]
**Describe the solution you'd like**
Ideally you should add true Infini-attention implementation there but I suppose you won't

**Additional context**
https://arxiv.org/pdf/2404.07143 - if you take a look at infini-attention paper, it's something totally different, I get it that the paper mentions both full attention and linear attention, but that doesn't mean you're just supposed to concatenate those, how tf did you even get an idea of doing that and calling it an implementation of infini-attention

**Comment by kyegomez** [comment]
@DanFosing im not done yet dumbass, if you don't like it submit a PR and fix it instead of bitching.
